spring:
  datasource:
    druid:
      biz-datasource:
        url: jdbc:h2:mem:bithon;MODE=mysql;
        username: sa
        password:
  h2:
    console:
      enabled: true
      path: /h2-ui

  #jOOQ Configuration
jooq:
  sql:
    dialect: H2