server:
  port: 9897
spring:
  application:
    name: collector-server
  profiles:
    active: dev

collector-thrift:
  enabled: true
  port:
    tracing: 9895
    event: 9896
    metric: 9898
    setting: 9899
  sink:
    type: local
    props:
      "[bootstrap.servers]": localhost:9092
      "[batch.size]": 65536
      "[buffer.memory]": 67108864
      "[linger.ms]": 50
      "[compression.type]": lz4
      "[max.in.flight.requests.per.connection]": 1
      "[retries]": 3

collector-kafka:
  enabled: false
  consumer:
    "[bootstrap.servers]": localhost:9092
    "[fetch.min.bytes]": 1024


logging:
  level:
    com.sbss.bithon.collector: debug