server:
    port: 9897
spring:
    application:
        name: collector-server
    profiles:
        active: dev

collector-service:
    enabled: true
    port:
        tracing: 9895
        event:   9896
        metric:  9898
        setting: 9899

logging:
    level:
        com.sbss.bithon.collector: debug