// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebRequestMetrics.proto

package org.bithon.component.brpc.example.protobuf;

/**
 * Protobuf type {@code org.bithon.component.brpc.example.protobuf.WebRequestMetrics}
 */
public final class WebRequestMetrics extends
    org.bithon.shaded.com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.bithon.component.brpc.example.protobuf.WebRequestMetrics)
    WebRequestMetricsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WebRequestMetrics.newBuilder() to construct.
  private WebRequestMetrics(org.bithon.shaded.com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WebRequestMetrics() {
    uri_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new WebRequestMetrics();
  }

  @Override
  public final org.bithon.shaded.com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final org.bithon.shaded.com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return WebRequestMetricsOuterClass.internal_static_org_bithon_component_brpc_example_protobuf_WebRequestMetrics_descriptor;
  }

  @Override
  protected org.bithon.shaded.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return WebRequestMetricsOuterClass.internal_static_org_bithon_component_brpc_example_protobuf_WebRequestMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            WebRequestMetrics.class, Builder.class);
  }

  public static final int URI_FIELD_NUMBER = 1;
  private volatile Object uri_;
  /**
   * <code>string uri = 1;</code>
   * @return The uri.
   */
  @Override
  public String getUri() {
    Object ref = uri_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      org.bithon.shaded.com.google.protobuf.ByteString bs = 
          (org.bithon.shaded.com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      uri_ = s;
      return s;
    }
  }
  /**
   * <code>string uri = 1;</code>
   * @return The bytes for uri.
   */
  @Override
  public org.bithon.shaded.com.google.protobuf.ByteString
      getUriBytes() {
    Object ref = uri_;
    if (ref instanceof String) {
      org.bithon.shaded.com.google.protobuf.ByteString b = 
          org.bithon.shaded.com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      uri_ = b;
      return b;
    } else {
      return (org.bithon.shaded.com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COSTNANOTIME_FIELD_NUMBER = 2;
  private long costNanoTime_;
  /**
   * <code>int64 costNanoTime = 2;</code>
   * @return The costNanoTime.
   */
  @Override
  public long getCostNanoTime() {
    return costNanoTime_;
  }

  public static final int REQUESTS_FIELD_NUMBER = 3;
  private long requests_;
  /**
   * <code>int64 requests = 3;</code>
   * @return The requests.
   */
  @Override
  public long getRequests() {
    return requests_;
  }

  public static final int COUNT4XX_FIELD_NUMBER = 4;
  private long count4Xx_;
  /**
   * <code>int64 count4xx = 4;</code>
   * @return The count4xx.
   */
  @Override
  public long getCount4Xx() {
    return count4Xx_;
  }

  public static final int COUNT5XX_FIELD_NUMBER = 5;
  private long count5Xx_;
  /**
   * <code>int64 count5xx = 5;</code>
   * @return The count5xx.
   */
  @Override
  public long getCount5Xx() {
    return count5Xx_;
  }

  public static final int REQUESTBYTES_FIELD_NUMBER = 6;
  private long requestBytes_;
  /**
   * <code>int64 requestBytes = 6;</code>
   * @return The requestBytes.
   */
  @Override
  public long getRequestBytes() {
    return requestBytes_;
  }

  public static final int RESPONSEBYTES_FIELD_NUMBER = 7;
  private long responseBytes_;
  /**
   * <code>int64 responseBytes = 7;</code>
   * @return The responseBytes.
   */
  @Override
  public long getResponseBytes() {
    return responseBytes_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(org.bithon.shaded.com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!org.bithon.shaded.com.google.protobuf.GeneratedMessageV3.isStringEmpty(uri_)) {
      org.bithon.shaded.com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uri_);
    }
    if (costNanoTime_ != 0L) {
      output.writeInt64(2, costNanoTime_);
    }
    if (requests_ != 0L) {
      output.writeInt64(3, requests_);
    }
    if (count4Xx_ != 0L) {
      output.writeInt64(4, count4Xx_);
    }
    if (count5Xx_ != 0L) {
      output.writeInt64(5, count5Xx_);
    }
    if (requestBytes_ != 0L) {
      output.writeInt64(6, requestBytes_);
    }
    if (responseBytes_ != 0L) {
      output.writeInt64(7, responseBytes_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!org.bithon.shaded.com.google.protobuf.GeneratedMessageV3.isStringEmpty(uri_)) {
      size += org.bithon.shaded.com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uri_);
    }
    if (costNanoTime_ != 0L) {
      size += org.bithon.shaded.com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, costNanoTime_);
    }
    if (requests_ != 0L) {
      size += org.bithon.shaded.com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, requests_);
    }
    if (count4Xx_ != 0L) {
      size += org.bithon.shaded.com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, count4Xx_);
    }
    if (count5Xx_ != 0L) {
      size += org.bithon.shaded.com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, count5Xx_);
    }
    if (requestBytes_ != 0L) {
      size += org.bithon.shaded.com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, requestBytes_);
    }
    if (responseBytes_ != 0L) {
      size += org.bithon.shaded.com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, responseBytes_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof WebRequestMetrics)) {
      return super.equals(obj);
    }
    WebRequestMetrics other = (WebRequestMetrics) obj;

    if (!getUri()
        .equals(other.getUri())) return false;
    if (getCostNanoTime()
        != other.getCostNanoTime()) return false;
    if (getRequests()
        != other.getRequests()) return false;
    if (getCount4Xx()
        != other.getCount4Xx()) return false;
    if (getCount5Xx()
        != other.getCount5Xx()) return false;
    if (getRequestBytes()
        != other.getRequestBytes()) return false;
    if (getResponseBytes()
        != other.getResponseBytes()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + URI_FIELD_NUMBER;
    hash = (53 * hash) + getUri().hashCode();
    hash = (37 * hash) + COSTNANOTIME_FIELD_NUMBER;
    hash = (53 * hash) + org.bithon.shaded.com.google.protobuf.Internal.hashLong(
        getCostNanoTime());
    hash = (37 * hash) + REQUESTS_FIELD_NUMBER;
    hash = (53 * hash) + org.bithon.shaded.com.google.protobuf.Internal.hashLong(
        getRequests());
    hash = (37 * hash) + COUNT4XX_FIELD_NUMBER;
    hash = (53 * hash) + org.bithon.shaded.com.google.protobuf.Internal.hashLong(
        getCount4Xx());
    hash = (37 * hash) + COUNT5XX_FIELD_NUMBER;
    hash = (53 * hash) + org.bithon.shaded.com.google.protobuf.Internal.hashLong(
        getCount5Xx());
    hash = (37 * hash) + REQUESTBYTES_FIELD_NUMBER;
    hash = (53 * hash) + org.bithon.shaded.com.google.protobuf.Internal.hashLong(
        getRequestBytes());
    hash = (37 * hash) + RESPONSEBYTES_FIELD_NUMBER;
    hash = (53 * hash) + org.bithon.shaded.com.google.protobuf.Internal.hashLong(
        getResponseBytes());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static WebRequestMetrics parseFrom(
      java.nio.ByteBuffer data)
      throws org.bithon.shaded.com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WebRequestMetrics parseFrom(
      java.nio.ByteBuffer data,
      org.bithon.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.bithon.shaded.com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WebRequestMetrics parseFrom(
      org.bithon.shaded.com.google.protobuf.ByteString data)
      throws org.bithon.shaded.com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WebRequestMetrics parseFrom(
      org.bithon.shaded.com.google.protobuf.ByteString data,
      org.bithon.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.bithon.shaded.com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WebRequestMetrics parseFrom(byte[] data)
      throws org.bithon.shaded.com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WebRequestMetrics parseFrom(
      byte[] data,
      org.bithon.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.bithon.shaded.com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WebRequestMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return org.bithon.shaded.com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static WebRequestMetrics parseFrom(
      java.io.InputStream input,
      org.bithon.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.bithon.shaded.com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static WebRequestMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return org.bithon.shaded.com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static WebRequestMetrics parseDelimitedFrom(
      java.io.InputStream input,
      org.bithon.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.bithon.shaded.com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static WebRequestMetrics parseFrom(
      org.bithon.shaded.com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return org.bithon.shaded.com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static WebRequestMetrics parseFrom(
      org.bithon.shaded.com.google.protobuf.CodedInputStream input,
      org.bithon.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return org.bithon.shaded.com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(WebRequestMetrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      org.bithon.shaded.com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.bithon.component.brpc.example.protobuf.WebRequestMetrics}
   */
  public static final class Builder extends
      org.bithon.shaded.com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.bithon.component.brpc.example.protobuf.WebRequestMetrics)
      WebRequestMetricsOrBuilder {
    public static final org.bithon.shaded.com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WebRequestMetricsOuterClass.internal_static_org_bithon_component_brpc_example_protobuf_WebRequestMetrics_descriptor;
    }

    @Override
    protected org.bithon.shaded.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WebRequestMetricsOuterClass.internal_static_org_bithon_component_brpc_example_protobuf_WebRequestMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WebRequestMetrics.class, Builder.class);
    }

    // Construct using org.bithon.component.brpc.example.protobuf.WebRequestMetrics.newBuilder()
    private Builder() {

    }

    private Builder(
        org.bithon.shaded.com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      uri_ = "";

      costNanoTime_ = 0L;

      requests_ = 0L;

      count4Xx_ = 0L;

      count5Xx_ = 0L;

      requestBytes_ = 0L;

      responseBytes_ = 0L;

      return this;
    }

    @Override
    public org.bithon.shaded.com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return WebRequestMetricsOuterClass.internal_static_org_bithon_component_brpc_example_protobuf_WebRequestMetrics_descriptor;
    }

    @Override
    public WebRequestMetrics getDefaultInstanceForType() {
      return WebRequestMetrics.getDefaultInstance();
    }

    @Override
    public WebRequestMetrics build() {
      WebRequestMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public WebRequestMetrics buildPartial() {
      WebRequestMetrics result = new WebRequestMetrics(this);
      result.uri_ = uri_;
      result.costNanoTime_ = costNanoTime_;
      result.requests_ = requests_;
      result.count4Xx_ = count4Xx_;
      result.count5Xx_ = count5Xx_;
      result.requestBytes_ = requestBytes_;
      result.responseBytes_ = responseBytes_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        org.bithon.shaded.com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        org.bithon.shaded.com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        org.bithon.shaded.com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        org.bithon.shaded.com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        org.bithon.shaded.com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(org.bithon.shaded.com.google.protobuf.Message other) {
      if (other instanceof WebRequestMetrics) {
        return mergeFrom((WebRequestMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(WebRequestMetrics other) {
      if (other == WebRequestMetrics.getDefaultInstance()) return this;
      if (!other.getUri().isEmpty()) {
        uri_ = other.uri_;
        onChanged();
      }
      if (other.getCostNanoTime() != 0L) {
        setCostNanoTime(other.getCostNanoTime());
      }
      if (other.getRequests() != 0L) {
        setRequests(other.getRequests());
      }
      if (other.getCount4Xx() != 0L) {
        setCount4Xx(other.getCount4Xx());
      }
      if (other.getCount5Xx() != 0L) {
        setCount5Xx(other.getCount5Xx());
      }
      if (other.getRequestBytes() != 0L) {
        setRequestBytes(other.getRequestBytes());
      }
      if (other.getResponseBytes() != 0L) {
        setResponseBytes(other.getResponseBytes());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        org.bithon.shaded.com.google.protobuf.CodedInputStream input,
        org.bithon.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              uri_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              costNanoTime_ = input.readInt64();

              break;
            } // case 16
            case 24: {
              requests_ = input.readInt64();

              break;
            } // case 24
            case 32: {
              count4Xx_ = input.readInt64();

              break;
            } // case 32
            case 40: {
              count5Xx_ = input.readInt64();

              break;
            } // case 40
            case 48: {
              requestBytes_ = input.readInt64();

              break;
            } // case 48
            case 56: {
              responseBytes_ = input.readInt64();

              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (org.bithon.shaded.com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private Object uri_ = "";
    /**
     * <code>string uri = 1;</code>
     * @return The uri.
     */
    public String getUri() {
      Object ref = uri_;
      if (!(ref instanceof String)) {
        org.bithon.shaded.com.google.protobuf.ByteString bs =
            (org.bithon.shaded.com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string uri = 1;</code>
     * @return The bytes for uri.
     */
    public org.bithon.shaded.com.google.protobuf.ByteString
        getUriBytes() {
      Object ref = uri_;
      if (ref instanceof String) {
        org.bithon.shaded.com.google.protobuf.ByteString b = 
            org.bithon.shaded.com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uri_ = b;
        return b;
      } else {
        return (org.bithon.shaded.com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uri = 1;</code>
     * @param value The uri to set.
     * @return This builder for chaining.
     */
    public Builder setUri(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uri_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string uri = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUri() {
      
      uri_ = getDefaultInstance().getUri();
      onChanged();
      return this;
    }
    /**
     * <code>string uri = 1;</code>
     * @param value The bytes for uri to set.
     * @return This builder for chaining.
     */
    public Builder setUriBytes(
        org.bithon.shaded.com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uri_ = value;
      onChanged();
      return this;
    }

    private long costNanoTime_ ;
    /**
     * <code>int64 costNanoTime = 2;</code>
     * @return The costNanoTime.
     */
    @Override
    public long getCostNanoTime() {
      return costNanoTime_;
    }
    /**
     * <code>int64 costNanoTime = 2;</code>
     * @param value The costNanoTime to set.
     * @return This builder for chaining.
     */
    public Builder setCostNanoTime(long value) {
      
      costNanoTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 costNanoTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCostNanoTime() {
      
      costNanoTime_ = 0L;
      onChanged();
      return this;
    }

    private long requests_ ;
    /**
     * <code>int64 requests = 3;</code>
     * @return The requests.
     */
    @Override
    public long getRequests() {
      return requests_;
    }
    /**
     * <code>int64 requests = 3;</code>
     * @param value The requests to set.
     * @return This builder for chaining.
     */
    public Builder setRequests(long value) {
      
      requests_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 requests = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequests() {
      
      requests_ = 0L;
      onChanged();
      return this;
    }

    private long count4Xx_ ;
    /**
     * <code>int64 count4xx = 4;</code>
     * @return The count4xx.
     */
    @Override
    public long getCount4Xx() {
      return count4Xx_;
    }
    /**
     * <code>int64 count4xx = 4;</code>
     * @param value The count4xx to set.
     * @return This builder for chaining.
     */
    public Builder setCount4Xx(long value) {
      
      count4Xx_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 count4xx = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount4Xx() {
      
      count4Xx_ = 0L;
      onChanged();
      return this;
    }

    private long count5Xx_ ;
    /**
     * <code>int64 count5xx = 5;</code>
     * @return The count5xx.
     */
    @Override
    public long getCount5Xx() {
      return count5Xx_;
    }
    /**
     * <code>int64 count5xx = 5;</code>
     * @param value The count5xx to set.
     * @return This builder for chaining.
     */
    public Builder setCount5Xx(long value) {
      
      count5Xx_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 count5xx = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount5Xx() {
      
      count5Xx_ = 0L;
      onChanged();
      return this;
    }

    private long requestBytes_ ;
    /**
     * <code>int64 requestBytes = 6;</code>
     * @return The requestBytes.
     */
    @Override
    public long getRequestBytes() {
      return requestBytes_;
    }
    /**
     * <code>int64 requestBytes = 6;</code>
     * @param value The requestBytes to set.
     * @return This builder for chaining.
     */
    public Builder setRequestBytes(long value) {
      
      requestBytes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 requestBytes = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestBytes() {
      
      requestBytes_ = 0L;
      onChanged();
      return this;
    }

    private long responseBytes_ ;
    /**
     * <code>int64 responseBytes = 7;</code>
     * @return The responseBytes.
     */
    @Override
    public long getResponseBytes() {
      return responseBytes_;
    }
    /**
     * <code>int64 responseBytes = 7;</code>
     * @param value The responseBytes to set.
     * @return This builder for chaining.
     */
    public Builder setResponseBytes(long value) {
      
      responseBytes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 responseBytes = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseBytes() {
      
      responseBytes_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final org.bithon.shaded.com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final org.bithon.shaded.com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.bithon.component.brpc.example.protobuf.WebRequestMetrics)
  }

  // @@protoc_insertion_point(class_scope:org.bithon.component.brpc.example.protobuf.WebRequestMetrics)
  private static final WebRequestMetrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new WebRequestMetrics();
  }

  public static WebRequestMetrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final org.bithon.shaded.com.google.protobuf.Parser<WebRequestMetrics>
      PARSER = new org.bithon.shaded.com.google.protobuf.AbstractParser<WebRequestMetrics>() {
    @Override
    public WebRequestMetrics parsePartialFrom(
        org.bithon.shaded.com.google.protobuf.CodedInputStream input,
        org.bithon.shaded.com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.bithon.shaded.com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (org.bithon.shaded.com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (org.bithon.shaded.com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new org.bithon.shaded.com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static org.bithon.shaded.com.google.protobuf.Parser<WebRequestMetrics> parser() {
    return PARSER;
  }

  @Override
  public org.bithon.shaded.com.google.protobuf.Parser<WebRequestMetrics> getParserForType() {
    return PARSER;
  }

  @Override
  public WebRequestMetrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

