### Create an Console notification provider
POST http://localhost:9897/alerting/api/alert/notification/create
Content-Type: application/yaml

id: 1
type: console
name: console-1


### Create an HTTP notification provider
POST http://localhost:9897/alerting/api/alert/notification/create
Content-Type: application/json

{
  "id": "2",
  "type": "http",
  "name": "http-1",
  "url": "http://localhost:9897/api/no-exist",
  "headers": {
    "X-Fake": "value"
  }
}

### Create an Kafka notification provider
POST http://localhost:9897/alerting/api/alert/notification/create
Content-Type: application/json

{
  "id": "3",
  "name": "kafka",
  "type": "kafka",
  "bootstrapServer": "localhost:9092",
  "topic": "alert",
  "producerProps": {
    "request.ms": 100
  }
}

### Get all providers
POST http://localhost:9897/alerting/api/alert/notification/get


### DELETE an HTTP notification provider
POST http://localhost:9897/alerting/api/alert/notification/delete?id=1

