#
# The configuration below shows the ability that run two pipelines in one application.
# This is mainly for local development and test, not for real deployment.
#
# In this demo, the first pipelines consume data to Kafka,
# and the other consumes data from Kafka into storage
#
bithon:
  pipelines:
    # Pipelines that consume data from brpc-collector to kafka
    brpc-event-kafka:
      type: events
      receivers:
        - type: brpc
      exporters:
        - type: kafka
          props:
            topic: bithon-events
            "[bootstrap.servers]": localhost:9092
            "[batch.size]": 65536
            "[buffer.memory]": 67108864
            "[linger.ms]": 50
            "[compression.type]": lz4
            "[max.in.flight.requests.per.connection]": 1
            "[retries]": 3

    brpc-metric-kafka:
      type: metrics
      receivers:
        - type: brpc
      exporters:
        - type: kafka
          props:
            topic: bithon-metrics
            "[bootstrap.servers]": localhost:9092
            "[batch.size]": 65536
            "[buffer.memory]": 67108864
            "[linger.ms]": 50
            "[compression.type]": lz4
            "[max.in.flight.requests.per.connection]": 1
            "[retries]": 3

    brpc-traces-kafka:
      type: traces
      receivers:
        - type: brpc
      exporters:
        - type: kafka
          props:
            topic: bithon-spans
            "[bootstrap.servers]": localhost:9092
            "[batch.size]": 65536
            "[buffer.memory]": 67108864
            "[linger.ms]": 50
            "[compression.type]": lz4
            "[max.in.flight.requests.per.connection]": 1
            "[retries]": 3

    #
    # Default pipelines that consume data from Kafka to local
    #
    events:
      enabled: true
      receivers:
        - type: kafka
          props:
            topic: bithon-events
            concurrency: 1
            pollTimeout: 1000
            ackTime: 5000
            "[group.id]": bithon-events-consumer
            "[bootstrap.servers]": localhost:9092
            "[fetch.min.bytes]": 1048576
      exporters:
        - type: store

    metrics:
      enabled: true
      receivers:
        - type: kafka
          props:
            topic: bithon-metrics
            concurrency: 1
            pollTimeout: 1000
            ackTime: 5000
            "[group.id]": bithon-metrics-consumer
            "[bootstrap.servers]": localhost:9092
            "[fetch.min.bytes]": 524288
      exporters:
        - type: store

    traces:
      enabled: true
      receivers:
        - type: kafka
          props:
            topic: bithon-spans
            concurrency: 1
            pollTimeout: 1000
            ackTime: 5000
            "[group.id]": bithon-spans-consumer
            "[bootstrap.servers]": localhost:9092
            "[fetch.min.bytes]": 1048576
      transforms:
      exporters:
        - type: store


logging:
  level:
    org.bithon.collector: debug
