collector-brpc:
  enabled: true
  port:
    tracing: 9895
    event: 9896
    metric: 9898
    ctrl: 9899
  sinks:
    event:
      type: local
    metrics:
      type: local
    tracing:
      type: local

collector-http:
  enabled: true
  tracing:
    clickhouseApplications:
      - clickhouse

collector-controller:
  permission:
    rules:
      - application:
          type: startwith
          pattern: bithon-
        token: "525"

logging:
  level:
    org.bithon.collector: debug
