#
# This all-in-one profile is just an example.
# It combines other profiles to enable all modules in a single application.
#
spring:
  config:
    import:
      - classpath:application-module-controller.yml
      - classpath:application-module-receiver.yml
      - classpath:application-module-pipeline-to-local.yml
      - classpath:application-module-storage-h2.yml
      - classpath:application-module-webapp.yml
      - classpath:application-module-alerting.yml
      - classpath:application-module-security.yml
