collector-kafka:
  enabled: true
  metrics:
    topic: bithon-metrics
    concurrency: 1
    pollTimeout: 1000
    ackTime: 5000
    "[group.id]": bithon-metrics-consumer
    "[bootstrap.servers]": localhost:9092
    "[fetch.min.bytes]": 524288
  event:
    topic: bithon-events
    concurrency: 1
    pollTimeout: 1000
    ackTime: 5000
    "[group.id]": bithon-events-consumer
    "[bootstrap.servers]": localhost:9092
    "[fetch.min.bytes]": 1048576
  tracing:
    topic: bithon-spans
    concurrency: 1
    pollTimeout: 1000
    ackTime: 5000
    "[group.id]": bithon-spans-consumer
    "[bootstrap.servers]": localhost:9092
    "[fetch.min.bytes]": 1048576


logging:
  level:
    org.bithon.collector: debug

server:
  port: 19898