#
# This file demonstrates configuring the Bithon server to use those databases that support JDBC as underlying storage.
# Currently, only H2 has been tested, so H2 is configured in this file.
#
bithon:
  storage:
    tracing:
      type: jdbc
      enabled: true
      ttl:
        enabled: true
        ttl: P1D
        cleanPeriod: PT3M
    metric:
      type: jdbc
      enabled: true
      ttl:
        enabled: true
        ttl: P1D
        cleanPeriod: PT3M
    event:
      type: jdbc
      enabled: true
      ttl:
        enabled: true
        ttl: P1D
        cleanPeriod: PT3M
    meta:
      type: jdbc
      enabled: true
      ttl:
        enabled: true
        ttl: PT5M
        cleanPeriod: PT3M
    setting:
      type: jdbc
      enabled: true
    web:
      type: jdbc
    providers:
      jdbc:
        enabled: true
        url: jdbc:h2:mem:bithon;DB_CLOSE_DELAY=-1;MODE=mysql;
        username: sa

spring:
  h2:
    console:
      enabled: true
      path: /h2-ui
      settings:
        web-allow-others: true

#
# Suppress useless and boring error logging
#
logging:
  level:
    org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator: OFF