bithon:
  pipelines:
    events:
      enabled: true
      receivers:
        - type: brpc
      exporters:
        - type: store

    metrics:
      enabled: true
      receivers:
        - type: brpc
      exporters:
        - type: store

    traces:
      enabled: true
      receivers:
        - type: brpc
        - type: bithon-trace-http
        - type: otlp-trace-grpc
        - type: otlp-trace-http
      processors:
        - type: drop
          expr: endsWith(clazz,  'UriNormalizer')
        - type: url-sanitize-transform
          sensitiveParameters:
            "[http.uri]": password
            "[http.url]": password
            "uri": password
        - type: builtin-span-transform
      mapping:
        - type: uri
          tags:
            "[http.uri]": ["query_id"]
            "[http.url]": ["query_id"]
            "uri": ["query_id"]
        - type: name
          tags: ["clickhouse.query_id", "druid.query_id"]
      exporters:
        - type: store


logging:
  level:
    org.bithon.collector: debug
