bithon:
  agent-controller:
    enabled: true
    port: 9899
    permission:
      rules:
        - application:
            type: startwith
            pattern: bithon-
          token: "525"

  receivers:
    metrics:
      brpc:
        enabled: true
        port: 9898
      http:
        enabled: true
    events:
      brpc:
        enabled: true
        port: 9896
    traces:
      brpc:
        enabled: true
        port: 9895
      http:
        enabled: true
      otel-http:
        enabled: true

  pipelines:
    events:
      enabled: true
      receivers:
        - type: brpc
      exporters:
        - type: store

    metrics:
      enabled: true
      receivers:
        - type: brpc
      exporters:
        - type: store

    traces:
      enabled: true
      receivers:
        - type: brpc
      processors:
        - type: filter
          expr: clazz <> 'org.bithon.server.sink.common.service.UriNormalizer'
        - type: url-sanitize-transform
          sensitiveParameters:
            - password
        - type: builtin-span-transform
      exporters:
        - type: store


logging:
  level:
    org.bithon.collector: debug
