bithon:
  storage:
    tracing: clickhouse
    metric: clickhouse
    event: clickhouse
    meta: clickhouse
    provider:
      type: clickhouse
      parameters:
        #url: jdbc:h2:mem:bithon;MODE=mysql;
        #username: sa
        url: jdbc:clickhouse://localhost:8123/default?date_time_input_format=best_effort
        driverClassName: ru.yandex.clickhouse.ClickHouseDriver
        username: default
        password:

spring:
  datasource:
    druid:
      biz-datasource:
        url: jdbc:h2:mem:bithon;MODE=mysql;
        username: sa
        password:
  h2:
    console:
      enabled: true
      path: /h2-ui