#
# This configuration file demonstrates configuring the server with both clickhouse and H2 databases as storage
#
bithon:
  storage:
    tracing:
      provider: clickhouse
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    metric:
      provider: clickhouse
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    event:
      provider: clickhouse
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    meta:
      provider: clickhouse
      enabled: true

    setting:
      provider: jdbc
      enabled: true

    web:
      provider: jdbc2

    providers:
      jdbc:
        url: jdbc:h2:mem:bithon;MODE=mysql;
        username: sa
      jdbc2:
        type: jdbc
        url: jdbc:h2:mem:bithon2;MODE=mysql;
        username: sa
      clickhouse:
        # data source parameters
        url: jdbc:clickhouse://localhost:8123/bithon?decompress=1&compress=1&nullAsDefault=2
        driverClassName: com.clickhouse.jdbc.ClickHouseDriver
        username: default
        password:
        # cluster parameters
        # cluster: test_cluster_two_shards_localhost
        # engine: MergeTree

spring:
  h2:
    console:
      enabled: true
      path: /h2-ui
      settings:
        web-allow-others: true

#
# Suppress useless and boring error logging
#
logging:
  level:
    org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator: OFF