bithon:
  storage:
    tracing: jdbc
    metric: jdbc
    event: jdbc
    meta: jdbc
    setting: jdbc
    provider:
      type: jdbc
      parameters:
        url: jdbc:h2:mem:bithon;MODE=mysql;
        username: sa

spring:
  h2:
    console:
      enabled: true
      path: /h2-ui
      settings:
        web-allow-others: true