#
# This file demonstrates configuring the Bithon server to use ClickHouse as underlying storage
#
bithon:
  storage:
    tracing:
      provider: clickhouse
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    metric:
      provider: clickhouse
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    event:
      provider: clickhouse
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    meta:
      provider: clickhouse
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    setting:
      provider: clickhouse
      enabled: true
    web:
      provider: clickhouse
    providers:
      clickhouse:
        url: jdbc:clickhouse://localhost:8123/bithon
        username: default
        password:
        #
        # If the deployment is on a sharded-based ClickHouse cluster, fill the following parameters
        #cluster: test_shard_localhost
        #onDistributedTable: true
        # can be MergeTree or ReplicateMergeTree(xxxx)
        #engine: MergeTree
