bithon:
  pipelines:
    events:
      enabled: true
      receivers:
        - type: brpc
      exporters:
        - type: store

    metrics:
      enabled: true
      receivers:
        - type: brpc
      exporters:
        - type: store

    traces:
      enabled: true
      receivers:
        - type: brpc
        - type: bithon-trace-http
        - type: otlp-trace-grpc
        - type: otlp-trace-http
      processors:
          # drop spans
        - type: drop
          expr: clazz endsWith 'UriNormalizer'
          # drop successful and quick(<1ms) health check requests
        - type: drop
          expr: tags['http.url'] in ('/actuator/info', '/status/health') AND parentSpanId = '' AND tags['http.status'] = '200' AND costTime < 1000
          # sanitize sensitive parameters
        - type: url-sanitize-transform
          sensitiveParameters:
            "[http.uri]": password
            "[http.url]": password
            "uri": password
          # built-in span transform
        - type: builtin-span-transform
      mapping:
        - type: uri
          tags:
            "[http.uri]": ["query_id"]
            "[http.url]": ["query_id"]
            "uri": ["query_id"]
        - type: name
          tags: ["clickhouse.query_id", "druid.query_id", "druid.sql_query_id"]
      exporters:
        - type: store


logging:
  level:
    org.bithon.collector: debug
