#
# This configuration file demonstrates configuring the server with both clickhouse and H2 databases as storage
#
bithon:
  storage:
    tracing:
      type: clickhouse
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    metric:
      type: clickhouse
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    event:
      type: clickhouse
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    meta:
      type: clickhouse
    setting:
      type: jdbc
    providers:
      jdbc:
        enabled: true
        url: jdbc:h2:mem:bithon;MODE=mysql;
        username: sa
      clickhouse:
        enabled: true
        # data source parameters
        url: jdbc:clickhouse://localhost:8123/bithon
        driverClassName: ru.yandex.clickhouse.ClickHouseDriver
        username: default
        password:
        # cluster parameters
        # cluster: test_cluster_two_shards_localhost
        # engine: MergeTree
spring:
  h2:
    console:
      enabled: true
      path: /h2-ui
      settings:
        web-allow-others: true
