# This property must exist to enable the webapp module
bithon:
  web:
    service:
      enabled: true

#
# Some web-server configurations
# Not mandatory
#
server:
  port: 9897
  compression:
    enabled: true
    min-response-size: 4096
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain
      - application/octet-stream
      - text/event-stream  # Enable compression for SSE
