#
# This all-in-one profile is just an example.
# It combines other profiles to enable webapp, collector and use the H2 database as storage.
#
spring:
  config:
    import:
      - application-controller.yml
      - application-receiver.yml
      - application-pipeline-to-local.yml
      - application-storage-mysql.yml
      - application-webapp.yml
      - application-alerting.yml
      - application-security.yml
