#
# This configuration file demonstrates configuring the server with both clickhouse and H2 databases as storage
#
bithon:
  storage:
    tracing:
      provider: ck
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    metric:
      provider: ck
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    event:
      provider: ck
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    meta:
      provider: ck
      enabled: true

    setting:
      provider: h2-1
      enabled: true

    dashboard:
      provider: mysql-1

    providers:
      h2-1:
        type: h2
        url: jdbc:h2:mem:bithon;MODE=mysql;
        username: sa

      mysql-1:
        type: mysql
        url: jdbc:mysql://localhost:3306/bithon
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root

      ck:
        type: clickhouse
        # data source parameters
        url: jdbc:clickhouse://localhost:8123/bithon?decompress=1&compress=1&nullAsDefault=2
        driverClassName: com.clickhouse.jdbc.ClickHouseDriver
        username: default
        password:
        # cluster parameters
        # cluster: test_cluster_two_shards_localhost
        # engine: MergeTree

spring:
  h2:
    console:
      enabled: true
      path: /h2-ui
      settings:
        web-allow-others: true

#
# Suppress useless and boring error logging
#
logging:
  level:
    org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator: OFF