#
# This file demonstrates configuring the Bithon server to use those databases that support JDBC as underlying storage.
# Currently, only MySQL has been tested, so MySQL is configured in this file.
#
bithon:
  storage:
    tracing:
      enabled: true
      provider: mysql-local
      ttl:
        enabled: true
        ttl: P1D
        cleanPeriod: PT1M

    metric:
      enabled: true
      provider: mysql-local
      ttl:
        enabled: true
        ttl: P1D
        cleanPeriod: PT1M

    event:
      enabled: true
      provider: mysql-local
      ttl:
        enabled: true
        ttl: P1D
        cleanPeriod: PT1M

    meta:
      enabled: true
      provider: mysql-local
      ttl:
        enabled: true
        ttl: PT5M
        cleanPeriod: PT1M

    setting:
      enabled: true
      provider: mysql-local

    dashboard:
      enabled: true
      provider: mysql-local

    alerting:
      all:
        provider: mysql-local
        ttl:
          enabled: true
          ttl: P1D
          cleanPeriod: PT3M

      log:
        provider: mysql-local
        ttl:
          enabled: true
          ttl: P1D
          cleanPeriod: PT3M

    providers:
      mysql-local:
        type: mysql

        # Make sure the database has been created
        # 'serverTimezone' is not configured here so that the client detects it automatically
        # You can also set it explicitly if you want, e.g., serverTimezone=UTC if the MySQL server is configured in UTC timezone
        # To check the timezone of your MySQL server, you can run the following command in MySQL CLI:
        #   SELECT @@global.time_zone, @@session.time_zone;
        # or SELECT NOW(), UTC_TIMESTAMP(); which shows the current time in both the configured timezone and UTC timezone
        url: jdbc:mysql://localhost:3306/bithon?useSSL=false&allowPublicKeyRetrieval=true
        # com.mysql.cj.jdbc.Driver is the driver class name for MySQL 5
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root

#
# Suppress useless and boring error logging
#
logging:
  level:
    org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator: OFF