bithon:
  storage:
    tracing: clickhouse
    metric: clickhouse
    event: clickhouse
    meta: clickhouse
    provider:
      type: clickhouse
      parameters:
        # data source parameters
        url: jdbc:clickhouse://localhost:8123/bithon
        driverClassName: ru.yandex.clickhouse.ClickHouseDriver
        username: default
        password:
        # cluster parameters
        cluster: test_cluster_two_shards_localhost
        # engine: MergeTree


