#
# This file demonstrates configuring the Bithon server to use ClickHouse as underlying storage
#
bithon:
  storage:
    tracing:
      enabled: true
      provider: clickhouse
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M

    metric:
      enabled: true
      provider: clickhouse
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M

    event:
      enabled: true
      provider: clickhouse
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M

    meta:
      enabled: true
      provider: clickhouse
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M

    setting:
      enabled: true
      provider: clickhouse

    dashboard:
      enabled: true
      provider: clickhouse

    alerting:
      all:
        provider: clickhouse
        ttl:
          enabled: true
          ttl: P1D
          cleanPeriod: PT3M
      log:
        provider: clickhouse
        ttl:
          enabled: true
          ttl: P1D
          cleanPeriod: PT3M

    providers:
      clickhouse:
        url: jdbc:clickhouse://localhost:8123/bithon?use_server_time_zone=true
        username: default
        password:
        #
        # If the deployment is on a sharded-based ClickHouse cluster, fill the following parameters
        #cluster: test_shard_localhost
        #onDistributedTable: true
        # can be MergeTree or ReplicateMergeTree(xxxx)
        #engine: MergeTree
        #ttl: toStartOfDay(timestamp) + INTERVAL 1 DAY MOVE TO VOLUME 'disk1'
