# This configuration file demonstrates the alerting deployment in one process.
bithon:
  alerting:
    evaluator:
      enabled: true
      scheduler:
        cron: 15 0/1 * 1/1 * ?
      # Where the evaluator module uses the notification services
      notification-service: discovery
    manager:
      enabled: true
      allow-anonymous: true
    notification:
      enabled: true
