#
# This file demonstrates configuring the Bithon server to use ClickHouse as underlying storage
#
bithon:
  storage:
    tracing:
      type: clickhouse
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    metric:
      type: clickhouse
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    event:
      type: clickhouse
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    meta:
      type: clickhouse
      enabled: true
    setting:
      type: clickhouse
      enabled: true
    providers:
      clickhouse:
        enabled: true
        # data source parameters
        url: jdbc:clickhouse://localhost:8123/bithon
        driverClassName: ru.yandex.clickhouse.ClickHouseDriver
        username: default
        password:
        # ------More parameters----
        # cluster: test_cluster_two_shards_localhost
        # engine: MergeTree
