collector-brpc:
  enabled: true
  port:
    tracing: 9895
    event: 9896
    metric: 9898
    ctrl: 9899
  sink:
    type: local
    props:
      "[bootstrap.servers]": localhost:9092
      "[batch.size]": 65536
      "[buffer.memory]": 67108864
      "[linger.ms]": 50
      "[compression.type]": lz4
      "[max.in.flight.requests.per.connection]": 1
      "[retries]": 3

collector-kafka:
  enabled: false
  metrics:
    topic: bithon-metrics
    "[bootstrap.servers]": localhost:9092
    "[fetch.min.bytes]": 524288
  event:
    topic: bithon-events
    "[bootstrap.servers]": localhost:9092
    "[fetch.min.bytes]": 1048576
  tracing:
    topic: bithon-spans
    "[bootstrap.servers]": localhost:9092
    "[fetch.min.bytes]": 1048576

collector-http:
  enabled: true
  tracing:
    clickhouseApplications:
      - clickhouse

logging:
  level:
    org.bithon.collector: debug
