bithon:
  agent-controller:
    enabled: true
    port: 9899
    permission:
      # The following define a global rule to ALLOW any operation from any user.
      # Refer to the PermissionConfig to know more about the configuration
      enabled: false
      rbac:
        users:
          - name: "*"
            permissions:
              - operation: RW
                resource: "*"
                application: "*"

