bithon:
  storage:
    tracing: jdbc
    metric: jdbc
    event: jdbc
    meta: jdbc
    provider:
      type: jdbc
      parameters:
        url: jdbc:h2:mem:bithon;MODE=mysql;
        username: sa
        password:

spring:
  datasource:
    druid:
      biz-datasource:
        url: jdbc:h2:mem:bithon;MODE=mysql;
        username: sa
        password:
  h2:
    console:
      enabled: true
      path: /h2-ui