#
# This all-in-one profile is just an example.
# It combines other profiles to enable webapp, collector and use the H2 database as storage.
#
spring:
  profiles:
    include:
      - collector-to-local
      - storage-jdbc
      - webapp