#
# This all-in-one profile is just an example.
# It combines other profiles to enable webapp, collector and use the H2 database as storage.
#
spring:
  config:
    import:
      - classpath:application-controller.yml
      - classpath:application-receiver.yml
      - classpath:application-pipeline-to-local.yml
      - classpath:application-storage-h2.yml
      - classpath:application-webapp.yml
      - classpath:application-alerting.yml
      - classpath:application-security.yml
