collector-brpc:
  enabled: true
  port:
    tracing: 9895
    event: 9896
    metric: 9898
    ctrl: 9899

collector-http:
  enabled: true

collector-otel:
  enabled: true

collector-controller:
  permission:
    rules:
      - application:
          type: startwith
          pattern: bithon-
        token: "525"

bithon:
  pipelines:
    events:
      enabled: true
      receivers:
        - type: brpc
      exporters:
        - type: store

    metrics:
      enabled: true
      receivers:
        - type: brpc
      exporters:
        - type: store

    traces:
      enabled: true
      receivers:
        - type: brpc
      transforms:
      exporters:
        - type: store


logging:
  level:
    org.bithon.collector: debug
