#
# This file demonstrates configuring the Bithon server to use those databases that support JDBC as underlying storage.
# Currently, only H2 has been tested, so H2 is configured in this file.
#
bithon:
  storage:
    tracing:
      enabled: true
      provider: h2-local
      ttl:
        enabled: true
        ttl: P1D
        cleanPeriod: PT1M
      indexes:
        # A demo of how the index works, can be removed in production
        map:
          "[http.method]": 1
    metric:
      enabled: true
      provider: h2-local
      ttl:
        enabled: true
        ttl: P1D
        cleanPeriod: PT1M
    event:
      enabled: true
      provider: h2-local
      ttl:
        enabled: true
        ttl: P1D
        cleanPeriod: PT1M
    meta:
      enabled: true
      provider: h2-local
      ttl:
        enabled: true
        ttl: PT5M
        cleanPeriod: PT1M
    setting:
      enabled: true
      provider: h2-local
    dashboard:
      enabled: true
      provider: h2-local

    alerting:
      all:
        provider: h2-local
        ttl:
          enabled: true
          ttl: P1D
          cleanPeriod: PT3M

      log:
        provider: h2-local
        ttl:
          enabled: true
          ttl: P1D
          cleanPeriod: PT3M

    providers:
      h2-local:
        type: h2
        url: jdbc:h2:mem:bithon;DB_CLOSE_DELAY=-1;MODE=mysql;
        username: sa

spring:
  h2:
    console:
      enabled: true
      path: /h2-ui
      settings:
        web-allow-others: true

#
# Suppress useless and boring error logging
#
logging:
  level:
    org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator: OFF