collector-thrift:
  enabled: false
  port:
    tracing: 9895
    event: 9896
    metric: 9898
    ctrl: 9899
  sink:
    type: local
    props:
      "[bootstrap.servers]": localhost:9092
      "[batch.size]": 65536
      "[buffer.memory]": 67108864
      "[linger.ms]": 50
      "[compression.type]": lz4
      "[max.in.flight.requests.per.connection]": 1
      "[retries]": 3

collector-brpc:
  enabled: true
  port:
    tracing: 9895
    event: 9896
    metric: 9898
    ctrl: 9899
  sink:
    type: local
    props:
      "[bootstrap.servers]": localhost:9092
      "[batch.size]": 65536
      "[buffer.memory]": 67108864
      "[linger.ms]": 50
      "[compression.type]": lz4
      "[max.in.flight.requests.per.connection]": 1
      "[retries]": 3

collector-kafka:
  enabled: false
  consumer:
    "[bootstrap.servers]": localhost:9092
    "[fetch.min.bytes]": 1024

logging:
  level:
    org.bithon.collector: debug

spring:
  datasource:
    druid:
      biz-datasource:
        url: jdbc:h2:mem:bithon;MODE=mysql;
        username: sa
        password:
  h2:
    console:
      enabled: true
      path: /h2-ui

jooq:
  sql:
    dialect: H2


collector:
  event:
    ttl: P1D
    cleanPeriod: PT3M
