#
# This file demonstrates configuring the Bithon server to use ClickHouse as underlying storage
#
bithon:
  storage:
    tracing:
      type: clickhouse
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    metric:
      type: clickhouse
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    event:
      type: clickhouse
      enabled: true
      ttl:
        enabled: true
        ttl: P7D
        cleanPeriod: PT30M
    meta:
      type: clickhouse
      enabled: true
    setting:
      type: clickhouse
      enabled: true
    web:
      type: clickhouse
    providers:
      clickhouse:
        enabled: true
        #
        # Data source parameters
        #   nullAsDefault = 1, disabled null checking at the ClickHouse JDBC side,
        #   See: https://clickhouse.com/docs/en/integrations/language-clients/java/jdbc/#configuration
        #
        url: jdbc:clickhouse://localhost:8123/bithon?decompress=1&compress=1&nullAsDefault=1
        driverClassName: com.clickhouse.jdbc.ClickHouseDriver
        username: default
        password:
        #
        # More parameters about ClickHouse cluster, see ClickHouseConfig for more information.
        # eg:
        #
        # cluster: test_cluster_two_shards_localhost
        # engine: MergeTree
