# This property must exist to enable the webapp module
bithon:
  web:
    service:
      enabled: true

#
# Some web-server configurations
# Not mandatory
#
server:
  port: 9897
  compression:
    enabled: true
    min-response-size: 4096

#
# Cache settings for static resources
# Better to have
#
spring:
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 3600
          must-revalidate: true

