/**
 * Autogenerated by Thrift Compiler (0.11.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.keruyun.commons.agent.collector.enums;


/**
 * @author Roy Wesley
 * @date 2017/10/24 18:02
 * @todo 定义请求方式枚举类
 */
public enum HttpMethodEnum implements org.apache.thrift.TEnum {
    GET(0),
    POST(1),
    PUT(2),
    PATCH(3),
    DELETE(4),
    OPTIONS(5),
    HEAD(6),
    TRACE(7),
    CONNECT(8);

    private final int value;

    private HttpMethodEnum(int value) {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * @return null if the value is not found.
     */
    public static HttpMethodEnum findByValue(int value) {
        switch (value) {
            case 0:
                return GET;
            case 1:
                return POST;
            case 2:
                return PUT;
            case 3:
                return PATCH;
            case 4:
                return DELETE;
            case 5:
                return OPTIONS;
            case 6:
                return HEAD;
            case 7:
                return TRACE;
            case 8:
                return CONNECT;
            default:
                return null;
        }
    }
}
