/**
 * Autogenerated by Thrift Compiler (0.11.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.keruyun.commons.agent.collector.enums;


/**
 * @author Roy Wesley
 * @date 2017/10/24 18:02
 * @todo 定义Thrif传输协议枚举类
 */
public enum TransportProtocolEnum implements org.apache.thrift.TEnum {
    JSON(0),
    COMPACT(1),
    BINARY(2);

    private final int value;

    private TransportProtocolEnum(int value) {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * @return null if the value is not found.
     */
    public static TransportProtocolEnum findByValue(int value) {
        switch (value) {
            case 0:
                return JSON;
            case 1:
                return COMPACT;
            case 2:
                return BINARY;
            default:
                return null;
        }
    }
}
