#
#   Copyright 2020 bithon.org
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

FROM maven:3.8.1-jdk-8-slim as builder

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get -qq update \
    && apt-get -qq -y install --no-install-recommends git

COPY . /src
WORKDIR /src/shaded
RUN --mount=type=cache,target=/root/.m2 \
    mvn clean install

WORKDIR /src
RUN --mount=type=cache,target=/root/.m2 \
      mvn -pl agent -am clean package \
      -T 1C \
      -DskipTests

FROM amd64/busybox:1.30.0-glibc as busybox
FROM gcr.io/distroless/java:8

COPY --from=busybox /bin/busybox /busybox/busybox
RUN ["/busybox/busybox", "--install", "/bin"]

COPY --from=builder /src/agent/agent-distribution/target/agent-distribution/agent-distribution/ /opt/agent-distribution

CMD [""]