#
#   Copyright 2020 bithon.org
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

ARG JDK_VERSION=21

FROM maven:3.9.6-eclipse-temurin-${JDK_VERSION} as builder

ARG BUILD_FROM_SOURCE="true"

# The git is required to get the branch info during build
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get -qq update \
    && apt-get -qq -y install --no-install-recommends git

COPY . /src

# Build shaded
WORKDIR /src/shaded
RUN if [ "$BUILD_FROM_SOURCE" = "true" ]; then \
      mvn -ntp clean install -DskipTests -T 1C \
      ; fi

# Build jOOQ
WORKDIR /src/server/jOOQ
RUN if [ "$BUILD_FROM_SOURCE" = "true" ]; then \
      mvn -ntp clean install -DskipTests -T 1C \
      ; fi

# Build Server
WORKDIR /src
RUN if [ "$BUILD_FROM_SOURCE" = "true" ]; then \
      mvn -ntp -pl server/server-starter -am \
      clean package \
      -T 1C \
      -DskipTests \
    ; fi

FROM eclipse-temurin:${JDK_VERSION}
COPY --from=builder /src/server/server-starter/target/server-starter.jar /opt/bithon-server-starter.jar

RUN apt-get -qq update \
    && apt-get -qq -y install unzip \
    && apt-get -qq -y install wget \
    && apt-get -qq -y install libjemalloc-dev

COPY docker/startup.sh /startup.sh
RUN chmod +x /startup.sh \
  && mkdir -p /opt/shared/conf

ENV JAVA_OPTS ""
ENV APP_OPTS ""
ENV ENABLE_AGENT=true

# Remember to replace the URI to the URI of your own distribution
ENV AGENT_URI https://github.com/FrankChen021/bithon/releases/download/agent-distribution-latest/agent-distribution.zip

# Replace the glibc memory allocator to jemalloc
ENV LD_PRELOAD "/usr/lib/x86_64-linux-gnu/libjemalloc.so"

VOLUME /opt/shared/conf

WORKDIR /opt
ENTRYPOINT ["/startup.sh"]
