#
#   Copyright 2020 bithon.org
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

ARG JDK=8

FROM maven:3.8.1-jdk-${JDK}-slim as builder

ARG BUILD_FROM_SOURCE="true"

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get -qq update \
    && apt-get -qq -y install --no-install-recommends git

COPY . /src

# Build shaded
WORKDIR /src/shaded
RUN --mount=type=cache,target=/root/.m2 if [ "$BUILD_FROM_SOURCE" = "true" ]; then \
      mvn clean install -DskipTests \
      ; fi

# Build jOOQ
WORKDIR /src/server/jOOQ
RUN --mount=type=cache,target=/root/.m2 if [ "$BUILD_FROM_SOURCE" = "true" ]; then \
      mvn clean install -DskipTests \
      ; fi

# Build Server
WORKDIR /src
RUN --mount=type=cache,target=/root/.m2 if [ "$BUILD_FROM_SOURCE" = "true" ]; then \
      mvn -pl server/server-starter -am \
      clean package \
      -T 1C \
      -DskipTests \
    ; fi

FROM openjdk:${JDK}-slim
COPY --from=builder /src/server/server-starter/target/bithon-server-starter.jar /opt/bithon-server-starter.jar

RUN apt-get -qq update \
    && apt-get -qq -y install unzip \
    && apt-get -qq -y install wget

COPY docker/startup.sh /startup.sh
RUN chmod +x /startup.sh \
  && mkdir -p /opt/shared/conf

ENV JAVA_OPTS ""
ENV APP_OPTS ""
ENV WITH_AGENT=true
ENV AGENT_URI https://repo1.maven.org/maven2/org/bithon/agent/agent-distribution/1.1.0-RELEASE/agent-distribution-1.1.0-RELEASE.zip

VOLUME /opt/shared/conf

WORKDIR /opt
ENTRYPOINT ["/startup.sh"]
