#
#   Copyright 2020 bithon.org
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

FROM maven:3.9.6-eclipse-temurin-17 AS builder

ARG BUILD_FROM_SOURCE="true"

# The git is required to get the branch info during build
RUN if [ "$BUILD_FROM_SOURCE" = "true" ]; then \
      export DEBIAN_FRONTEND=noninteractive \
          && apt-get -qq update \
          && apt-get -qq -y install --no-install-recommends git \
      ; fi

COPY . /src
WORKDIR /src/shaded
RUN if [ "$BUILD_FROM_SOURCE" = "true" ]; then \
      mvn -ntp clean install -T 1C \
      ; fi

WORKDIR /src
RUN if [ "$BUILD_FROM_SOURCE" = "true" ]; then \
      mvn -ntp -P!server clean install -DskipTests -T 1C \
      ; fi

FROM openjdk:8-jre-alpine

COPY --from=builder /src/agent/agent-distribution/target/agent-distribution/agent-distribution/ /opt/agent-distribution

CMD [""]