/*
 * This file is generated by jOOQ.
 */
package org.bithon.server.storage.jdbc.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.bithon.server.storage.jdbc.common.jooq.DefaultSchema;
import org.bithon.server.storage.jdbc.common.jooq.Indexes;
import org.bithon.server.storage.jdbc.common.jooq.Keys;
import org.bithon.server.storage.jdbc.common.jooq.tables.records.BithonWebDashboardRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function9;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BithonWebDashboard extends TableImpl<BithonWebDashboardRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>bithon_web_dashboard</code>
     */
    public static final BithonWebDashboard BITHON_WEB_DASHBOARD = new BithonWebDashboard();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BithonWebDashboardRecord> getRecordType() {
        return BithonWebDashboardRecord.class;
    }

    /**
     * The column <code>bithon_web_dashboard.id</code>. Name, unique id
     */
    public final TableField<BithonWebDashboardRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(64).nullable(false), this, "Name, unique id");

    /**
     * The column <code>bithon_web_dashboard.folder</code>. Folder/Category
     */
    public final TableField<BithonWebDashboardRecord, String> FOLDER = createField(DSL.name("folder"), SQLDataType.VARCHAR(256).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "Folder/Category");

    /**
     * The column <code>bithon_web_dashboard.title</code>. Title
     */
    public final TableField<BithonWebDashboardRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(256).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "Title");

    /**
     * The column <code>bithon_web_dashboard.payload</code>. Schema in JSON
     */
    public final TableField<BithonWebDashboardRecord, String> PAYLOAD = createField(DSL.name("payload"), SQLDataType.CLOB.nullable(false), this, "Schema in JSON");

    /**
     * The column <code>bithon_web_dashboard.signature</code>. Signature of
     * payload field, currently SHA256 is applied
     */
    public final TableField<BithonWebDashboardRecord, String> SIGNATURE = createField(DSL.name("signature"), SQLDataType.VARCHAR(250).nullable(false), this, "Signature of payload field, currently SHA256 is applied");

    /**
     * The column <code>bithon_web_dashboard.createdAt</code>. Created Timestamp
     */
    public final TableField<BithonWebDashboardRecord, LocalDateTime> CREATEDAT = createField(DSL.name("createdAt"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "Created Timestamp");

    /**
     * The column <code>bithon_web_dashboard.lastModified</code>. Last modified
     * time
     */
    public final TableField<BithonWebDashboardRecord, LocalDateTime> LASTMODIFIED = createField(DSL.name("lastModified"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "Last modified time");

    /**
     * The column <code>bithon_web_dashboard.deleted</code>.
     */
    public final TableField<BithonWebDashboardRecord, Integer> DELETED = createField(DSL.name("deleted"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bithon_web_dashboard.visible</code>. if the dashboard is
     * visible to users
     */
    public final TableField<BithonWebDashboardRecord, Integer> VISIBLE = createField(DSL.name("visible"), SQLDataType.INTEGER.nullable(false), this, "if the dashboard is visible to users");

    private BithonWebDashboard(Name alias, Table<BithonWebDashboardRecord> aliased) {
        this(alias, aliased, null);
    }

    private BithonWebDashboard(Name alias, Table<BithonWebDashboardRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>bithon_web_dashboard</code> table reference
     */
    public BithonWebDashboard(String alias) {
        this(DSL.name(alias), BITHON_WEB_DASHBOARD);
    }

    /**
     * Create an aliased <code>bithon_web_dashboard</code> table reference
     */
    public BithonWebDashboard(Name alias) {
        this(alias, BITHON_WEB_DASHBOARD);
    }

    /**
     * Create a <code>bithon_web_dashboard</code> table reference
     */
    public BithonWebDashboard() {
        this(DSL.name("bithon_web_dashboard"), null);
    }

    public <O extends Record> BithonWebDashboard(Table<O> child, ForeignKey<O, BithonWebDashboardRecord> key) {
        super(child, key, BITHON_WEB_DASHBOARD);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.BITHON_WEB_DASHBOARD_IDX_WEB_DASHBOARD_CREATEDAT, Indexes.BITHON_WEB_DASHBOARD_IDX_WEB_DASHBOARD_LASTMODIFIED);
    }

    @Override
    public List<UniqueKey<BithonWebDashboardRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_BITHON_WEB_DASHBOARD_IDX_WEB_DASHBOARD_ID);
    }

    @Override
    public BithonWebDashboard as(String alias) {
        return new BithonWebDashboard(DSL.name(alias), this);
    }

    @Override
    public BithonWebDashboard as(Name alias) {
        return new BithonWebDashboard(alias, this);
    }

    @Override
    public BithonWebDashboard as(Table<?> alias) {
        return new BithonWebDashboard(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BithonWebDashboard rename(String name) {
        return new BithonWebDashboard(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BithonWebDashboard rename(Name name) {
        return new BithonWebDashboard(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BithonWebDashboard rename(Table<?> name) {
        return new BithonWebDashboard(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, String, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function9<? super String, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function9<? super String, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
