/*
 * This file is generated by jOOQ.
 */
package org.bithon.server.storage.jdbc.jooq.tables.records;


import java.sql.Timestamp;

import org.bithon.server.storage.jdbc.jooq.tables.BithonAlertChangelog;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Change logs of alert
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BithonAlertChangelogRecord extends UpdatableRecordImpl<BithonAlertChangelogRecord> implements Record7<Long, String, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = -183520288;

    /**
     * Setter for <code>bithon_alert_changelog.pk_id</code>. PK ID
     */
    public void setPkId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>bithon_alert_changelog.pk_id</code>. PK ID
     */
    public Long getPkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>bithon_alert_changelog.alert_id</code>. ID of Alert Object
     */
    public void setAlertId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bithon_alert_changelog.alert_id</code>. ID of Alert Object
     */
    public String getAlertId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bithon_alert_changelog.action</code>.
     */
    public void setAction(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bithon_alert_changelog.action</code>.
     */
    public String getAction() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bithon_alert_changelog.payload_before</code>. JSON formatted
     */
    public void setPayloadBefore(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bithon_alert_changelog.payload_before</code>. JSON formatted
     */
    public String getPayloadBefore() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bithon_alert_changelog.payload_after</code>. JSON formatted
     */
    public void setPayloadAfter(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bithon_alert_changelog.payload_after</code>. JSON formatted
     */
    public String getPayloadAfter() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bithon_alert_changelog.editor</code>.
     */
    public void setEditor(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bithon_alert_changelog.editor</code>.
     */
    public String getEditor() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bithon_alert_changelog.server_update_time</code>. 更新时间
     */
    public void setServerUpdateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>bithon_alert_changelog.server_update_time</code>. 更新时间
     */
    public Timestamp getServerUpdateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, String, String, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BithonAlertChangelog.BITHON_ALERT_CHANGELOG.PK_ID;
    }

    @Override
    public Field<String> field2() {
        return BithonAlertChangelog.BITHON_ALERT_CHANGELOG.ALERT_ID;
    }

    @Override
    public Field<String> field3() {
        return BithonAlertChangelog.BITHON_ALERT_CHANGELOG.ACTION;
    }

    @Override
    public Field<String> field4() {
        return BithonAlertChangelog.BITHON_ALERT_CHANGELOG.PAYLOAD_BEFORE;
    }

    @Override
    public Field<String> field5() {
        return BithonAlertChangelog.BITHON_ALERT_CHANGELOG.PAYLOAD_AFTER;
    }

    @Override
    public Field<String> field6() {
        return BithonAlertChangelog.BITHON_ALERT_CHANGELOG.EDITOR;
    }

    @Override
    public Field<Timestamp> field7() {
        return BithonAlertChangelog.BITHON_ALERT_CHANGELOG.SERVER_UPDATE_TIME;
    }

    @Override
    public Long component1() {
        return getPkId();
    }

    @Override
    public String component2() {
        return getAlertId();
    }

    @Override
    public String component3() {
        return getAction();
    }

    @Override
    public String component4() {
        return getPayloadBefore();
    }

    @Override
    public String component5() {
        return getPayloadAfter();
    }

    @Override
    public String component6() {
        return getEditor();
    }

    @Override
    public Timestamp component7() {
        return getServerUpdateTime();
    }

    @Override
    public Long value1() {
        return getPkId();
    }

    @Override
    public String value2() {
        return getAlertId();
    }

    @Override
    public String value3() {
        return getAction();
    }

    @Override
    public String value4() {
        return getPayloadBefore();
    }

    @Override
    public String value5() {
        return getPayloadAfter();
    }

    @Override
    public String value6() {
        return getEditor();
    }

    @Override
    public Timestamp value7() {
        return getServerUpdateTime();
    }

    @Override
    public BithonAlertChangelogRecord value1(Long value) {
        setPkId(value);
        return this;
    }

    @Override
    public BithonAlertChangelogRecord value2(String value) {
        setAlertId(value);
        return this;
    }

    @Override
    public BithonAlertChangelogRecord value3(String value) {
        setAction(value);
        return this;
    }

    @Override
    public BithonAlertChangelogRecord value4(String value) {
        setPayloadBefore(value);
        return this;
    }

    @Override
    public BithonAlertChangelogRecord value5(String value) {
        setPayloadAfter(value);
        return this;
    }

    @Override
    public BithonAlertChangelogRecord value6(String value) {
        setEditor(value);
        return this;
    }

    @Override
    public BithonAlertChangelogRecord value7(Timestamp value) {
        setServerUpdateTime(value);
        return this;
    }

    @Override
    public BithonAlertChangelogRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BithonAlertChangelogRecord
     */
    public BithonAlertChangelogRecord() {
        super(BithonAlertChangelog.BITHON_ALERT_CHANGELOG);
    }

    /**
     * Create a detached, initialised BithonAlertChangelogRecord
     */
    public BithonAlertChangelogRecord(Long pkId, String alertId, String action, String payloadBefore, String payloadAfter, String editor, Timestamp serverUpdateTime) {
        super(BithonAlertChangelog.BITHON_ALERT_CHANGELOG);

        set(0, pkId);
        set(1, alertId);
        set(2, action);
        set(3, payloadBefore);
        set(4, payloadAfter);
        set(5, editor);
        set(6, serverUpdateTime);
    }
}
