package org.bithon.server.storage.datasource.transformer;

import lombok.Getter;
import org.bithon.server.storage.datasource.input.IInputRow;

/**
 * @author Frank Chen
 * @date 11/4/22 11:54 PM
 */
abstract public class AbstractSimpleTransformer implements ITransformer {

    /**
     * the field name generated by this transformer
     */
    @Getter
    protected final String name;

    protected AbstractSimpleTransformer(String name) {
        this.name = name;
    }

    @Override
    public void transform(IInputRow inputRow) {
        Object obj = this.transformInternal(inputRow);
        if (obj != null) {
            inputRow.updateColumn(name, obj);
        }
    }

    protected abstract Object transformInternal(IInputRow row);
}
