# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Agent Build

on:
  push:
    branches: [master]
    paths:
      - "agent/**"
      - "component/**"
      - "shaded/**"
      - "license/**"
      - "dev/**"
      - "pom.xml"
      - ".github/workflows/build-agent.yml"
  pull_request:
    branches: [master]
    paths:
      - "agent/**"
      - "component/**"
      - "shaded/**"
      - "license/**"
      - "dev/**"
      - "pom.xml"
      - ".github/workflows/build-agent.yml"

concurrency:
  # https://stackoverflow.com/questions/68418857/how-to-cancel-existing-runs-when-a-new-push-happens-on-github-actions-but-only
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On the master branch, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/master' && format('ci-master-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.artifact-info.outputs.name }}
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup JDK17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      #
      # separate shaded building from other modules because if it's built with other modules,
      # there might be library pollution in the agent-distribution
      #
      - name: Install shaded libs
        run: mvn clean install -T 1C -ntp --activate-profiles shaded -Dmaven.javadoc.skip=true -DskipTests

      - name: Compilation
        run: mvn clean install -T 1C -ntp --activate-profiles agent,component -Dmaven.javadoc.skip=true -DskipTests

      - name: Process test resources
        run: mvn test-compile -T 1C -ntp --activate-profiles agent,component -DskipTests

      - name: Verify test resources are built
        run: |
          echo "=== Verifying test resources are built and included in artifacts ==="
          # Check for MySQL test resources in target directories
          find agent/ -path "*/target/test-classes/*" -name "init-mysql*.sql" -type f
          find agent/ -path "*/target/test-classes/*" -name "logback-test.xml" -type f
          
          # List all test-classes directories that will be included in artifacts
          echo "=== Test-classes directories to be included in artifacts ==="
          find agent/ -name "test-classes" -type d | while read test_dir; do
            echo "Test-classes directory: $test_dir"
            if [ -d "$test_dir" ]; then
              echo "Contents:"
              ls -la "$test_dir" || echo "Cannot list contents"
              if [ -d "$test_dir/resources" ]; then
                echo "Resources:"
                find "$test_dir/resources" -type f
              fi
            fi
          done

      - name: Code Check
        run: mvn --ntp -T 1C -P-server com.github.spotbugs:spotbugs-maven-plugin:check dependency:analyze-only

      - name: Verify agent distribution was built
        run: |
          if [ -f "agent/agent-distribution/target/agent-distribution.zip" ]; then
            echo "✅ Agent distribution built successfully: $(ls -la agent/agent-distribution/target/agent-distribution.zip)"
          else
            echo "❌ Agent distribution not found after build!"
            echo "Contents of agent/agent-distribution/target/:"
            ls -la agent/agent-distribution/target/ || echo "Directory doesn't exist"
            echo "Available ZIP files in project:"
            find . -name "*.zip" -type f
            exit 1
          fi

      - name: Set artifact info
        id: artifact-info
        run: echo "name=build-artifacts-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-info.outputs.name }}
          path: |
            **/target/classes/**
            **/target/test-classes/**
            **/target/**/*.jar
            **/target/**/*.tar
            **/target/**/*.zip
            **/pom.xml
            pom.xml
            ~/.m2/repository
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # LTS versions using temurin
          - java-version: "8"
            distribution: "temurin"
          - java-version: "11"
            distribution: "temurin"
          - java-version: "17"
            distribution: "temurin"
          - java-version: "21"
            distribution: "temurin"
          - java-version: "22"
            distribution: "zulu"
          - java-version: "23"
            distribution: "zulu"
          - java-version: "24"
            distribution: "zulu"
          - java-version: "25"
            distribution: "temurin"
          # Non-LTS versions using zulu (better historical support)
          - java-version: "9"
            distribution: "zulu"
          - java-version: "10"
            distribution: "zulu"
          - java-version: "12"
            distribution: "zulu"
          - java-version: "13"
            distribution: "zulu"
          - java-version: "14"
            distribution: "zulu"
          - java-version: "15"
            distribution: "zulu"
          - java-version: "16"
            distribution: "zulu"
          - java-version: "18"
            distribution: "zulu"
          - java-version: "19"
            distribution: "zulu"
          - java-version: "20"
            distribution: "zulu"
      fail-fast: false
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK ${{ matrix.java-version }} (${{ matrix.distribution }})
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}

      - name: Restore Maven repository
        run: |
          if [ -d ".m2/repository" ]; then
            mkdir -p ~/.m2
            cp -r .m2/repository ~/.m2/
            echo "✅ Maven repository restored"
          else
            echo "❌ No Maven repository found in artifacts"
            exit 1
          fi

      - name: Restore build artifacts to correct locations
        run: |
          echo "=== Moving artifacts from GitHub Actions paths to workspace paths ==="
          # Find and move target directories from artifact paths to workspace paths
          if [ -d "work/bithon/bithon" ]; then
            echo "Found artifacts in work/bithon/bithon/, copying to workspace..."
            # Copy all target directories to the correct locations
            find work/bithon/bithon -name "target" -type d | while read target_dir; do
              # Extract the relative path after work/bithon/bithon/
              relative_path=${target_dir#work/bithon/bithon/}
              workspace_target="$relative_path"
              echo "Copying $target_dir to $workspace_target"
              mkdir -p "$(dirname "$workspace_target")"
              cp -r "$target_dir" "$workspace_target"
            done
            echo "✅ Artifacts copied to workspace locations"
          else
            echo "No work/bithon/bithon directory found, artifacts may already be in correct location"
          fi

          echo "=== Verifying target directories now exist ==="
          ls -la agent/agent-core/target/ || echo "Still no target directory"
          find agent/ -name "*Test.class" -type f | head -5

      - name: Verify test resources are available
        run: |
          echo "=== Checking for TestContainers SQL init scripts ==="
          # Check for MySQL test resources
          find agent/ -name "init-mysql*.sql" -type f | head -10
          find agent/ -name "logback-test.xml" -type f | head -10
          
          # Check test-classes directories
          echo "=== Checking test-classes directories ==="
          find agent/ -name "test-classes" -type d | while read test_classes_dir; do
            echo "Contents of $test_classes_dir:"
            ls -la "$test_classes_dir" || echo "Directory not accessible"
            # Check for resources subdirectory
            if [ -d "$test_classes_dir/resources" ]; then
              echo "Resources in $test_classes_dir/resources:"
              find "$test_classes_dir/resources" -type f | head -10
            fi
          done
          
          # Verify specific MySQL test resources
          echo "=== Verifying MySQL test resources ==="
          for mysql_version in mysql5 mysql6 mysql8; do
            echo "Checking $mysql_version resources:"
            find agent/ -path "*/$mysql_version/*/test-classes" -type d | while read test_dir; do
              if [ -d "$test_dir" ]; then
                echo "Found test-classes for $mysql_version: $test_dir"
                ls -la "$test_dir" || echo "Cannot list contents"
                if [ -d "$test_dir/resources" ]; then
                  echo "Resources in $test_dir/resources:"
                  find "$test_dir/resources" -type f
                fi
              fi
            done
          done

      - name: Rebuild test resources if missing
        run: |
          echo "=== Rebuilding test resources if they are missing ==="
          # Check if any MySQL test resources are missing
          MISSING_RESOURCES=false
          for mysql_version in mysql5 mysql6 mysql8; do
            for resource in "init-mysql${mysql_version#mysql}.sql" "logback-test.xml"; do
              if ! find agent/ -path "*/$mysql_version/*/test-classes/*" -name "$resource" -type f | grep -q .; then
                echo "❌ Missing resource: $resource for $mysql_version"
                MISSING_RESOURCES=true
              fi
            done
          done
          
          if [ "$MISSING_RESOURCES" = true ]; then
            echo "=== Rebuilding test resources ==="
            mvn test-compile -T 1C -ntp --activate-profiles agent,component -DskipTests
            
            echo "=== Verifying resources after rebuild ==="
            find agent/ -path "*/target/test-classes/*" -name "init-mysql*.sql" -type f
            find agent/ -path "*/target/test-classes/*" -name "logback-test.xml" -type f
          else
            echo "✅ All test resources are available"
          fi

      - name: Set up TestContainers environment
        run: |
          echo "=== Setting up TestContainers environment ==="
          # TestContainers requires Docker to be available
          # GitHub Actions runners have Docker pre-installed
          echo "Docker version:"
          docker --version
          
          # TestContainers configuration
          echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV
          echo "TESTCONTAINERS_HOST_OVERRIDE=localhost" >> $GITHUB_ENV
          
          # Enable TestContainers debug logging for troubleshooting
          echo "TESTCONTAINERS_DEBUG=true" >> $GITHUB_ENV
          
          # Set TestContainers to use the Docker daemon
          echo "DOCKER_HOST=unix:///var/run/docker.sock" >> $GITHUB_ENV
          
          echo "✅ TestContainers environment configured"
          echo "Environment variables set:"
          echo "TESTCONTAINERS_RYUK_DISABLED=$TESTCONTAINERS_RYUK_DISABLED"
          echo "TESTCONTAINERS_HOST_OVERRIDE=$TESTCONTAINERS_HOST_OVERRIDE"
          echo "TESTCONTAINERS_DEBUG=$TESTCONTAINERS_DEBUG"
          echo "DOCKER_HOST=$DOCKER_HOST"

      - name: Verify Docker is running
        run: |
          echo "=== Verifying Docker is available for TestContainers ==="
          docker info
          echo "Docker daemon is running and accessible"

      # Execute UT with the current JDK version - skip compilation, just run tests
      - name: Run tests with JDK ${{ matrix.java-version }}
        run: |
          echo "=== Running tests with TestContainers support ==="
          # Ensure test resources are in classpath by running from project root
          mvn surefire:test --activate-profiles agent -P-server -ntp -Dtest.working.directory=$PWD
        env:
          # Ensure TestContainers environment variables are available
          TESTCONTAINERS_RYUK_DISABLED: true
          TESTCONTAINERS_HOST_OVERRIDE: localhost
          TESTCONTAINERS_DEBUG: true
          DOCKER_HOST: unix:///var/run/docker.sock
          # Ensure Maven can find test resources
          MAVEN_OPTS: "-Djava.class.path=$PWD"

  release:
    needs: [build, test]
    runs-on: ubuntu-latest
    # Run on master branch AND if both build and test jobs succeeded
    if: (github.ref == 'refs/heads/master') && needs.build.result == 'success' && needs.test.result == 'success'
    concurrency:
      group: "release-agent-distribution"
      cancel-in-progress: false
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}

      - name: Debug downloaded artifacts structure
        run: |
          echo "=== Root directory contents ==="
          ls -la
          echo "=== Looking for agent-distribution.zip anywhere ==="
          find . -name "*agent-distribution*" -type f
          echo "=== Directory structure (first 3 levels) ==="
          find . -maxdepth 3 -type d | sort

      - name: Restore Maven repository
        run: |
          if [ -d ".m2/repository" ]; then
            mkdir -p ~/.m2
            cp -r .m2/repository ~/.m2/
            echo "✅ Maven repository restored for release"
          fi

      - name: Find agent distribution files and set paths
        id: find-agent-files
        run: |
          # Check for ZIP file
          if [ -f "agent/agent-distribution/target/agent-distribution.zip" ]; then
            AGENT_ZIP_PATH="agent/agent-distribution/target/agent-distribution.zip"
            echo "✅ Found agent ZIP at expected path: $AGENT_ZIP_PATH"
          else
            # Search for the file anywhere if not found at expected location
            AGENT_ZIP_PATH=$(find . -name "agent-distribution.zip" -type f | head -1)
            if [ -n "$AGENT_ZIP_PATH" ]; then
              echo "✅ Found agent ZIP at: $AGENT_ZIP_PATH"
              # Remove leading ./ if present
              AGENT_ZIP_PATH=${AGENT_ZIP_PATH#./}
            else
              echo "❌ Error: agent-distribution.zip not found anywhere!"
              echo "=== Available ZIP files: ==="
              find . -name "*.zip" -type f
              exit 1
            fi
          fi

          # Check for TAR file
          if [ -f "agent/agent-distribution/target/agent-distribution.tar" ]; then
            AGENT_TAR_PATH="agent/agent-distribution/target/agent-distribution.tar"
            echo "✅ Found agent TAR at expected path: $AGENT_TAR_PATH"
          else
            # Search for the file anywhere if not found at expected location
            AGENT_TAR_PATH=$(find . -name "agent-distribution.tar" -type f | head -1)
            if [ -n "$AGENT_TAR_PATH" ]; then
              echo "✅ Found agent TAR at: $AGENT_TAR_PATH"
              # Remove leading ./ if present
              AGENT_TAR_PATH=${AGENT_TAR_PATH#./}
            else
              echo "❌ Error: agent-distribution.tar not found anywhere!"
              echo "=== Available TAR files: ==="
              find . -name "*.tar" -type f
              exit 1
            fi
          fi

          echo "agent-zip-path=$AGENT_ZIP_PATH" >> $GITHUB_OUTPUT
          echo "agent-tar-path=$AGENT_TAR_PATH" >> $GITHUB_OUTPUT
          echo "ZIP path: $AGENT_ZIP_PATH"
          echo "TAR path: $AGENT_TAR_PATH"
          ls -la "$AGENT_ZIP_PATH" "$AGENT_TAR_PATH"

      #
      # Follow steps are for release, we only enable them for changes on the master branch
      # Delete both tag and release if we have successfully built and tested the agent
      #
      # https://github.com/marketplace/actions/delete-tag-and-release
      - name: Delete previous agent tag and release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        continue-on-error: true
        with:
          delete_release: true # This deletes both the release and the tag
          tag_name: agent-distribution-latest
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait before recreating release
        run: sleep 5

      - name: Release agent ZIP
        uses: svenstaro/upload-release-action@v2
        with:
          body: "The latest agent built from commit ${{ github.sha }}"
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: agent-distribution-latest
          tag: agent-distribution-latest
          asset_name: agent-distribution.zip
          file: ${{ steps.find-agent-files.outputs.agent-zip-path }}

      - name: Release agent TAR
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: agent-distribution-latest
          asset_name: agent-distribution.tar
          file: ${{ steps.find-agent-files.outputs.agent-tar-path }}

      - name: Verify release created
        run: |
          # Wait a moment for the release to be available
          sleep 10
          # Check if the release was created successfully
          RELEASE_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/agent-distribution-latest"
          if curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$RELEASE_URL" | grep -q '"tag_name"'; then
            echo "✅ Release verification successful"
          else
            echo "❌ Release verification failed - release may not have been created properly"
            exit 1
          fi
