# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: JDK8 Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup JDK8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      #
      # separate shaded building from other modules because if it's built with other modules,
      # there might be library pollution in the agent-distribution
      #
      - name: Install shaded libs
        run: mvn clean install -T 1C -ntp --activate-profiles shaded -Dmaven.javadoc.skip=true -DskipTests

      - name: Compilation
        run: mvn clean install -T 1C -ntp --activate-profiles jooq,server,agent,component -Dmaven.javadoc.skip=true -DskipTests

      - name: Code Check
        run: mvn --ntp -T 1C animal-sniffer:check checkstyle:checkstyle com.github.spotbugs:spotbugs-maven-plugin:4.2.2:check

      # https://github.com/marketplace/actions/delete-tag-and-release
      - name: Delete agent tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: false # default: false
          tag_name: agent-distribution-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release agent
        # if: github.ref == 'refs/heads/master'
        uses: svenstaro/upload-release-action@v2
        with:
          body: "The latest agent"
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: agent-distribution-latest
          tag: agent-distribution-latest
          asset_name: agent-distribution.zip
          file: agent/agent-distribution/target/agent-distribution.zip
