# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: JDK17 Server Build

on:
  push:
    branches: [master]
    paths-ignore:
      - "agent/**"
  pull_request:
    branches: [master]
    paths-ignore:
      - "agent/**"
      - ".github/workflows/build-agent.yml"
      - ".github/workflows/push-docker-agent-images.yml"

concurrency:
  # https://stackoverflow.com/questions/68418857/how-to-cancel-existing-runs-when-a-new-push-happens-on-github-actions-but-only
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On master, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/master' && format('ci-master-jdk17-{0}', github.sha) || format('ci-jdk17-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup JDK17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Compilation
        run: mvn clean install -T 1C -ntp --activate-profiles shaded,jooq,server,component -Dmaven.javadoc.skip=true -DskipTests

      - name: Code Check
        run: mvn --ntp -T 1C -P-agent animal-sniffer:check checkstyle:checkstyle com.github.spotbugs:spotbugs-maven-plugin:check
