name: Push Server Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup JDK8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build -t bithon/server -f docker/Dockerfile-server .
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_ACCESS_CODE }}" | docker login -u bithon --password-stdin

      - name: Push image
        run:  docker push bithon/server:latest